#!/bin/sh

# Entry point for Sigil on Unix systems.
# Adds linked Qt's lib directory to the LD_LIBRARY_PATH

QTLIB_DIR="${QT_LIBRARY_DIR}"

if [ -z "$LD_LIBRARY_PATH" ]; then
  LD_LIBRARY_PATH="$QTLIB_DIR"
else
  LD_LIBRARY_PATH="$QTLIB_DIR:$LD_LIBRARY_PATH"
fi

# Create an environment var for the Sigil helper directory.
if [ -z "$SIGIL_EXTRA_ROOT" ]; then
  SIGIL_EXTRA_ROOT="${CMAKE_INSTALL_PREFIX}/share/sigil"
  export SIGIL_EXTRA_ROOT
fi

export LD_LIBRARY_PATH

exec ${CMAKE_INSTALL_PREFIX}/lib/sigil/sigil "$@"

