#!/bin/sh

# Entry point for Sigil on Unix systems.
# Adds the package's bin directory to the LD_LIBRARY_PATH

QTLIB_DIR="${CMAKE_INSTALL_PREFIX}/share/sigil"

if [ -z "$LD_LIBRARY_PATH" ]; then
  LD_LIBRARY_PATH="$QTLIB_DIR"
else
  LD_LIBRARY_PATH="$QTLIB_DIR:$LD_LIBRARY_PATH"
fi

# Create an environment var for SIGIL_PLUGIN_LAUNCHERS
# since we've relocated the "real" sigil binary.
if [ -z "$SIGIL_EXTRA_ROOT" ]; then
  SIGIL_EXTRA_ROOT="$QTLIB_DIR"
  export SIGIL_EXTRA_ROOT
fi
export LD_LIBRARY_PATH

exec ${CMAKE_INSTALL_PREFIX}/lib/sigil/${DESTINATION_EXECUTABLE_NAME} "$@"

