#!/bin/sh

# Entry point for Sigil on Unix systems.
# Adds the package's bin directory to the LD_LIBRARY_PATH

QTLIB_DIR="${CMAKE_INSTALL_PREFIX}/lib/sigil"

if [ -z "$LD_LIBRARY_PATH" ]; then
  LD_LIBRARY_PATH="$QTLIB_DIR"
else
  LD_LIBRARY_PATH="$QTLIB_DIR:$LD_LIBRARY_PATH"
fi

# Create an environment var for the Sigil share directory location.
if [ -z "$SIGIL_SHARE_PREFIX" ]; then
  SIGIL_SHARE_PREFIX="${SHARE_INSTALL_PREFIX}"
  export SIGIL_SHARE_PREFIX
fi

# Not really needed anymore but left in for fringe cases
#if [ -z "$SIGIL_EXTRA_ROOT" ]; then
#  SIGIL_EXTRA_ROOT="${SIGIL_SHARE_ROOT}"
#  export SIGIL_EXTRA_ROOT
#fi

export LD_LIBRARY_PATH

exec ${CMAKE_INSTALL_PREFIX}/lib/sigil/sigil "$@"

