// ----------------------------------------------------------------
//  This file was generated from the XML error message source.
//  so do not edit this file directly!!
// ----------------------------------------------------------------

#include <xercesc/util/XercesDefs.hpp>

XERCES_CPP_NAMESPACE_BEGIN

const unsigned int CatId_XMLErrs = 1;
const unsigned int CatId_XMLValid = 2;
const unsigned int CatId_XMLExcepts = 3;
const unsigned int CatId_XMLDOMMsg = 4;

XERCES_CPP_NAMESPACE_END

